### ISSUE TITLE
No accounts.csv file

### ISSUE THREAD

**Issue by alexanderepolite** [TerrificTable/Jetbrains_Account_Generator#1]
Hello!  I was exploring repositories using the TempMail API and this looks interesting!

From what I have seen, the repository will fail as there is no accounts.csv file present.  This can be solved by creating an empty accounts.csv file before writing to it.

Also, I would like to ask that you wait 1 second between checking for emails to reduce load on my server.  Just a suggestion, otherwise you might get automatically rate-limited.

Please let me know if you create any other projects that use the TempMail.lol API :)

**Comment by TerrificTable** [comment]
> From what I have seen, the repository will fail as there is no accounts.csv file present. This can be solved by creating an empty accounts.csv file before writing to it.

I noticed that when using it on my Laptop


> Also, I would like to ask that you wait 1 second between checking for emails to reduce load on my server. Just a suggestion, otherwise you might get automatically rate-limited

I May implement a 1sec delay, when i tested it (aka i let it Run in the Background for a few hours and looked looked at how Many resources it uses) there was No Problem with Ratelimits or resources usage... But yea waiting 1-2secs between checking for E-Mails will be better than doing it without waiting.


I'am Not at Home at the Moment, i will Update the repository when i am Back home.


> Please let me know if you create any other projects that use the TempMail.lol API :)
You can follow me :)
